// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owsujqaaozisxsgidcmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93c3VqcWFhb3ppc3hzZ2lkY21nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTgwMTUsImV4cCI6MjA2ODkzNDAxNX0.tukRbqw1ZHUUNkdNlQfZ7ZnNqeBLYWFeOFoJratQLYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});